.gitignore
run-vera.sh
vera++/profiles/spinnaker.tcl
vera++/scripts/rules/F001.tcl
vera++/scripts/rules/F002.tcl
vera++/scripts/rules/L001.tcl
vera++/scripts/rules/L003.tcl
vera++/scripts/rules/L004.tcl
vera++/scripts/rules/L005.tcl
vera++/scripts/rules/L006.tcl
vera++/scripts/rules/T001.tcl
vera++/scripts/rules/T002.tcl
vera++/scripts/rules/T003.tcl
vera++/scripts/rules/T005.tcl
vera++/scripts/rules/T006.tcl
vera++/scripts/rules/T007.tcl
vera++/scripts/rules/T008.tcl
vera++/scripts/rules/T009.tcl
vera++/scripts/rules/T010.tcl
vera++/scripts/rules/T015.tcl
vera++/scripts/rules/T019.tcl

This is the code I've put together for basic C style checking. I've not yet finished tuning the exact profile of checks that describe what is considered to be best practice for SpiNNaker source, but it is fairly close.

C code style checking scripts

---

automatic_make.sh

this allows us to then insert the data gathering components into extra monitors cores.
depends upon:

Removal of re injector from spinnMan and into FEC

---

xml-support/algorithms.xsd

Changes to match https://github.com/SpiNNakerManchester/PACMAN/pull/135

Schema changes from PACMAN

---

automatic-spinnaker.mk
automatic_spinnaker_make.sh

Part of https://github.com/SpiNNakerManchester/spinnaker_tools/pull/75
Mainly code copied from https://github.com/SpiNNakerManchester/SupportScripts/pull/11
But spinn_common now has an install!

Dictionary for log messages

---

find_closest_git_version.py

A new script I need for the git integration in RemoteSpiNNaker.  I will merge this now - just doing a pull request for notification!

Find closest git version

---

setup.sh

remove stray semi-colon

---

actions/install-matplotlib/action.yml
actions/install-matplotlib/requirements.txt
actions/python-tools/action.yml

I know this install matplotlib in lots of places it is not needed
But is is a clean fix which avoids messing with setup.py

install matplotlib to avoid any version monsters

---

automatic_make.sh

Addded SpiNNGym
But checked it just skips directories it does not find

added SpiNNGym

---

automatic-spinnaker.mk
automatic_make.sh
automatic_make_debug.sh

SpiNNakerManchester/SpiNNakerGraphFrontEnd#178

GFE examples have moved

---

actions/checkout-spinn-deps/gitclone.sh
gitclone.sh

Update the gitclone scripts to also support tags

---

automatic_make.sh

Please merge this in after
and any other it depends on like
have been merged in

add SpiNNaker_PDP2 to automatic make

---

docstring_checker/directory_doc_checker.py
find_closest_git_version.py
spynnaker_mock.py
version/checker.py
version_checker.py

no need to support python2.7 any more!
should be done before
https://github.com/SpiNNakerManchester/PACMAN/pull/429

remove future import

---

actions/check-copyrights/action.yml

Don't know if the assumptions I made about URLs in the action apply yet.

Update rat version

---

actions/install-matplotlib/requirements.txt

Version update for matplotlib needs to be done here too.

Set matplotlib version for python 3.7

---

automatic_make_debug.sh

Some changes to the automatic_make_debug.sh script to go with the changes in https://github.com/SpiNNakerManchester/sPyNNaker/pull/1103

Update automatic make script that uses debug flags

---

get_jnlp.py

Adding script for getting jnlp from old servers for console redirection

Add get_jnlp.py script

---

actions/check-copyrights/action.yml
actions/check-copyrights/rat_asl20.xml

based on:
https://creadur.apache.org/rat/apache-rat-tasks/examples/basic.html

add checking for just the AppliedApacheSoftwareLicense20

---

actions/apt-get-install/action.yml

This should fix the problems @andrewgait reported in sPyNNaker.

Add apt-get update to Debian package installer

---

README.md

part of https://github.com/SpiNNakerManchester/sphinx8/pull/6

edit link to combined docs

---

actions/python-tools/action.yml

This reverts commit 6722d7c858b0bfb123b49059a6e03fddda483724.

Revert "enable turing off install pylint"

---

do_release_python.sh
install.sh
setup.sh
setup_install.sh
setup_sudo.sh
uninstall.sh

part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1075

Move DataType to FEC. Archive DataSpecification

---

actions/pylint/default_dict.txt

spell checker looks for JSON
impossible to test fully until in master

json package name

---

actions/cff-validator/action.yml

this needs reverting but must be in main to allow debugging

copy pynn-setup as a test

---

actions/pytest/action.yml

most of the changes happened in 
https://github.com/SpiNNakerManchester/SupportScripts/commit/de8b03fa99366ed95c5ea763d395b81ba8a2964c
This pr marks that and fixes some spellings

Overrides check

---

.github/workflows/python_checks.yml

Needed as https://github.com/SpiNNakerManchester/SpiNNMan/blob/master/spinnman_integration_tests/test_job.py fails with python 3.13.6 and 3.13.7
self = <spinnman_integration_tests.test_job.TestTransceiver testMethod=test_create_job>
def test_create_job(self) -> None:
try:
client = SpallocClient(self.spalloc_url)
except ConnectionError as ex:
raise unittest.SkipTest(str(ex))
job = client.create_job(
num_boards=2, machine_name=self.spalloc_machine)
with job:
job.wait_until_ready()
connections = job.get_connections()
self.assertGreaterEqual(len(connections), 2)
self.assertIn((0, 0), connections)
>           txrx = job.create_transceiver()
^^^^^^^^^^^^^^^^^^^^^^^^
spinnman_integration_tests/test_job.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …

temp cap python 3.13
